// SPDX-License-Identifier: MIT
pragma solidity 0.8.19;

interface IAddressTerminal {

    /**
    * @dev Returns the keccak256 hash of the string "TERMINAL".
    * This function is pure and does not modify the contract state.
    * @return bytes32 The keccak256 hash of the string "TERMINAL".
    */
    function terminalKey() external pure returns (bytes32);

    /**
    * @dev Returns the address stored in the contract state at the key generated by `terminalKey`.
    * This function is view and does not modify the contract state.
    * @return address The address stored in the contract state at the key generated by `terminalKey`.
    */
    function terminal() external view returns (address);
}